framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      # failed: 'doctrine://default?queue_name=failed'
      # sync: 'sync://'

      async_fetch_exchange_rate_from_cbr:
        dsn: '%env(MESSENGER_TRANSPORT_DSN_RABBITMQ)%'
        options:
          exchange:
            name: freedom_finance.rate_exchange.command
            type: direct
          queues:
            freedom_finance.rate_exchange.command.cbr:
              binding_keys: [ 'cbr' ]
        rate_limiter: cbr_api
        failure_transport: failure_fetch_exchange_rate_from_cbr

      failure_fetch_exchange_rate_from_cbr:
        dsn: '%env(MESSENGER_TRANSPORT_DSN_DOCTRINE)%'
        options:
          queue_name: fetch_exchange_rate_from_cbr
    routing:
      # Route your messages to the transports
      'App\Message\Command\FetchExchangeRatesFromCbrCommand': async_fetch_exchange_rate_from_cbr

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
